version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - '8080:8080'
#   db:
#     image: postgres:alpine
#     volumes:
#       - db-volume:/var/lib/postgresql/data

# volumes:
#   db-volume:
#     external: true
#     name: db-volume
